# Generated by Django 4.2.30 on 2026-10-01 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatments', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('treatments', 'Treatments'), ('appointments', 'Appointments'), ('pricing', 'Pricing'), ('aftercare', 'Aftercare')], db_index=True, default='general', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Skin & Hair Care Clinic', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('logo_dark', models.ImageField(blank=True, help_text='Logo variant for dark backgrounds', null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('about_short', models.TextField(blank=True, help_text='Short intro for the homepage hero section')),
                ('about_full', models.TextField(blank=True, help_text='Detailed text for the About Us page')),
                ('hero_image', models.ImageField(blank=True, help_text='Homepage hero background image', null=True, upload_to='site/')),
                ('about_image', models.ImageField(blank=True, help_text='Image shown on the About section / page', null=True, upload_to='site/')),
                ('phone_primary', models.CharField(blank=True, max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('email_primary', models.EmailField(blank=True, max_length=254)),
                ('email_secondary', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Include country code, e.g. +919876543210', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('working_hours_weekday', models.CharField(blank=True, help_text='e.g. Mon–Fri: 9:00 AM – 7:00 PM', max_length=100)),
                ('working_hours_weekend', models.CharField(blank=True, help_text='e.g. Sat: 9:00 AM – 2:00 PM', max_length=100)),
                ('google_maps_embed', models.TextField(blank=True, help_text='Full Google Maps embed <iframe> code')),
                ('google_maps_link', models.URLField(blank=True, help_text='Direct Google Maps link for the "Get Directions" button')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('footer_text', models.TextField(blank=True, help_text='Extra text shown in the site footer')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], db_index=True, default='new', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to the patient)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Enquiry',
                'verbose_name_plural': 'Contact Enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_contac_status_fefb7d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, help_text='e.g. Patient, Client', max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, help_text='Doctor this testimonial relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='doctors.doctor')),
                ('treatment', models.ForeignKey(blank=True, help_text='Treatment this testimonial relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='treatments.treatment')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_testim_created_b36113_idx')],
            },
        ),
    ]
