# Generated by Django 4.2.30 on 2026-10-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Clinic Page'), ('doctors', 'Doctors & Specialists Page'), ('treatments', 'Treatments Listing Page'), ('before_after', 'Before & After Results Page'), ('gallery', 'Clinic Gallery Page'), ('testimonials', 'Patient Reviews Page'), ('blog', 'Blog & Journal Page'), ('offers', 'Special Offers Page'), ('faq', 'Frequently Asked Questions Page'), ('contact', 'Contact & Location Page'), ('book_appointment', 'Book Appointment Page')], db_index=True, max_length=40, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='Custom SEO title for browser tab and search engines (leave blank for defaults)', max_length=200)),
                ('meta_description', models.CharField(blank=True, help_text='Meta description for search engine snippets (150–160 chars recommended)', max_length=320)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=300)),
                ('canonical_url', models.CharField(blank=True, help_text='Custom canonical URL (defaults to current page URL if blank)', max_length=300)),
                ('og_image', models.ImageField(blank=True, help_text='Custom social share banner image (1200x630px recommended)', null=True, upload_to='seo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page SEO Configuration',
                'verbose_name_plural': 'Pages SEO Configuration',
                'ordering': ['page'],
            },
        ),
    ]
