# Generated by Django 4.2.30 on 2026-10-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Gallery Category', 'verbose_name_plural': 'Gallery Categories'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order', '-uploaded_at'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
    ]
