# Generated by Django 4.2.30 on 2026-10-01 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(blank=True, help_text='Bootstrap icon class, e.g. bi-heart-pulse', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='treatments/categories/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Treatment Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('benefits', models.TextField(blank=True, help_text='Key benefits, one per line')),
                ('image', models.ImageField(blank=True, null=True, upload_to='treatments/')),
                ('banner_image', models.ImageField(blank=True, help_text='Wide banner image for the detail page header', null=True, upload_to='treatments/banners/')),
                ('duration', models.CharField(blank=True, help_text='e.g. 30–45 minutes', max_length=50)),
                ('sessions_required', models.CharField(blank=True, help_text='e.g. 4–6 sessions', max_length=100)),
                ('price_range', models.CharField(blank=True, help_text='e.g. ₹2,000 – ₹5,000', max_length=100)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='treatments.treatmentcategory')),
            ],
            options={
                'ordering': ['category__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_text', models.CharField(blank=True, help_text='e.g. 20% OFF, Buy 1 Get 1 Free', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treatments', models.ManyToManyField(blank=True, help_text='Treatments included in this offer', related_name='offers', to='treatments.treatment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['slug'], name='treatments__slug_bc3b56_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['is_featured', 'is_active'], name='treatments__is_feat_4e9700_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['is_active', 'end_date'], name='treatments__is_acti_f561c9_idx'),
        ),
    ]
