# Generated by Django 4.2.30 on 2026-10-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Special Offer / Package', 'verbose_name_plural': 'Special Offers & Packages'},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ['category__order', 'name'], 'verbose_name': 'Treatment / Procedure', 'verbose_name_plural': 'Treatments & Procedures'},
        ),
    ]
