# Generated by Django 4.2.30 on 2026-10-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Blog Article / Post', 'verbose_name_plural': 'Blog Articles & Posts'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Article Tag', 'verbose_name_plural': 'Article Tags'},
        ),
    ]
