# Generated by Django 4.2.30 on 2026-10-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Appointment Booking', 'verbose_name_plural': 'Appointment Bookings'},
        ),
    ]
