# Generated by Django 4.2.30 on 2026-10-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('designation', models.CharField(help_text='e.g. Dermatologist, Trichologist, Cosmetic Surgeon', max_length=200)),
                ('qualifications', models.CharField(blank=True, help_text='e.g. MBBS, MD (Dermatology), FAAD', max_length=300)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('banner_image', models.ImageField(blank=True, help_text='Banner for the doctor detail page', null=True, upload_to='doctors/banners/')),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of professional experience')),
                ('consultation_fee', models.CharField(blank=True, help_text='e.g. ₹500, ₹500 – ₹1,000', max_length=100)),
                ('available_days', models.CharField(blank=True, help_text='e.g. Mon–Fri, Mon/Wed/Fri', max_length=200)),
                ('available_time', models.CharField(blank=True, help_text='e.g. 10:00 AM – 4:00 PM', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treatments', models.ManyToManyField(blank=True, help_text='Treatments this doctor performs', related_name='doctors', to='treatments.treatment')),
            ],
            options={
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='doctors_doc_slug_3caa7e_idx'), models.Index(fields=['is_active', 'order'], name='doctors_doc_is_acti_a825b1_idx')],
            },
        ),
    ]
