# Generated by Django 4.2.30 on 2026-10-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Doctor / Specialist', 'verbose_name_plural': 'Doctors & Specialists'},
        ),
    ]
